language: node_js
sudo: false
matrix:
  include:
    - name: "Linux - Node 8"
      os: linux
      node_js: "8"
      env:
        - CXX=g++-4.9
        - CC=gcc-4.9
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.9
          - g++-4.9
    - name: "Linux - Node 10"
      os: linux
      node_js: "10"
      env:
        - CXX=g++-4.9
        - CC=gcc-4.9
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.9
          - g++-4.9
    - name: "Linux - Node 12"
      os: linux
      node_js: "12"
      env:
        - CXX=g++-4.9
        - CC=gcc-4.9
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.9
          - g++-4.9
    - name: "OS X - Node 8"
      os: osx
      node_js: "8"
      osx_image: xcode11
      compiler: clang
      env:
        - CXX=g++
        - CC=gcc
    - name: "OS X - Node 10"
      os: osx
      node_js: "10"
      osx_image: xcode11
      compiler: clang
      env:
        - CXX=g++
        - CC=gcc
    - name: "OS X - Node 12"
      os: osx
      node_js: "12"
      osx_image: xcode11
      compiler: clang
      env:
        - CXX=g++
        - CC=gcc
before_script:
- npm run build-debug
before_deploy:
- npm run build-release
- $(npm bin)/prebuild -r node -t 8.0.0 -t 10.0.0 -t 12.0.0
- $(npm bin)/prebuild -r electron -t 2.0.0 -t 3.0.0 -t 4.0.0 -t 5.0.0 -t 6.0.0 -t 7.0.0
deploy:
  provider: releases
  api_key:
    secure: XCFNqrapjrhQbj3r3CV4Sjpl182yCX2O9DP5AnZPMd5AvCeZPy0vm09JGU+6s8Z1X+olPj6SFm4200TT9ZWGd339N1vUxpW9JFj1nKUtFgD9zWf4532DBsIvHZNNF5kGdywxDiWNGlphAvZ/3ciVbyoadqm02Rw8vfNqRzB1debmQst8OOEw4yMBmORuWA945D15Fab9SKFB5WvWAfdPO0f94bBMZCNau+sd6fvOfkselfehl03Cbju/vMUEI7gOEc47HpTRrbLWDK4oWnuXS3wOnq+WXBGmBLbGpKofUR86oErl4H+yOYF3l99U0LtJoayTDoFNNEyh6mRpld4zoahPcyX9z0uXgQgwSvLBl0/u2mUOFhLDX4aRBI0RkNfDuV7JtIh1WD4ii2iRRRgP1l/4lcEHDycGxWNiL/vZlRl4QpSs2/3Ut5cMZL//3Cs5qxPOT/P7swQ2OAcUTTkIFbjkH9nn0vlHoN4vP4XBayLGzq0M57iIKsYC/ur+plCJMG9wvREQB7LuxERh0o6ayxRVrn4z7ajMn7hI2Xz/qPGWoNcsnn+rCB87abaPLM8NSXtj0ivxgbsvJk5NyuQHK+0wLndcFSNi29PklJlzTzBRPcQq+p0MH2jeA2Sj9tQb3AWzwwZ0bKGfYy23f1rCqGNKoqfkiEnkWPRjJRRxcuI=
  file: prebuilds/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: JoshuaWise/integer
    tags: true
    node_js: "12"
